FROM ubuntu:23.04

RUN sed -i 's/lunar/jammy/g' /etc/apt/sources.list

# Install build dependencies
RUN apt-get update && apt-get install -y \
    sudo \
    vim \
    nano \
    wget \
    make \
    cmake \
    build-essential \
    gdb \
    valgrind \
    software-properties-common \
    net-tools \
    libgtest-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
#
## Add PPA for g++-13
#RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test \
#    && apt-get update \
#    && apt install -y g++-13 \
#    && rm -f /usr/bin/g++ \
#    && rm -f /usr/bin/c++ \
#    && ln -s /usr/bin/g++-13 /usr/bin/g++ \
#    && ln -s /usr/bin/c++-13 /usr/bin/c++

# Set up user
RUN useradd --create-home --groups sudo --shell /bin/bash developer \
    && mkdir -p /etc/sudoers.d \
    && echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer \
    && chmod 0440 /etc/sudoers.d/developer

# Set the working directory and default entrypoint
USER developer
ENV HOME /home/developer
WORKDIR /home/developer/workspace/geompp
ENTRYPOINT ["/bin/bash"]
